### ISSUE TITLE
Errors when common prefix cannot be determined

### ISSUE THREAD

**Issue by daniellienert** [tobsto/tonumove#1]
If a filename only consists of digits or if the filename has no digit, the fixFileOrder method fails:

Digits:
```
Traceback (most recent call last):
  File "./tonumove.py", line 206, in <module>
    main()
  File "./tonumove.py", line 76, in main
    result = copy2Tonuino(folder, args.output)
  File "./tonumove.py", line 168, in copy2Tonuino
    ifiles_fixed = fixFileOrder(ifiles)
  File "./tonumove.py", line 102, in fixFileOrder
    while str.isdigit(f[lp + i]):
IndexError: string index out of range
```

No digits: 
```
Traceback (most recent call last):
  File "./tonumove.py", line 210, in <module>
    main()
  File "./tonumove.py", line 76, in main
    result = copy2Tonuino(folder, args.output)
  File "./tonumove.py", line 172, in copy2Tonuino
    ifiles_fixed = fixFileOrder(ifiles)
  File "./tonumove.py", line 110, in fixFileOrder
    trackNumbers.append(int(f[lp:lp + i]))
ValueError: invalid literal for int() with base 10: ''
```

Tried to fix it, but never coded in python.

**Comment by tobsto** [comment]
Thanks for reporting. I have no time to really fix this, but I disabled the fixing of the order of the files by default. Therefore it should work now. See new Readme
